=== csjx/realtime-data/conf/instrument.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  *  instrument.dtd
  *
  *  Copyright: 2016 Regents of the University of Hawaii and the
  *         School of Ocean and Earth Science and Technology 
  *
-->
<!-- 
  The following DTD represents a driver configuration  
  for a source instrument via serial, socket, or file connection.
  The driver then pushes data samples to an RBNB Data Turbine server
  based on the provided parameters.

  To validate XML documents that adhere to this DTD, use a validator like
  xmlstarlet:
  $ cd conf
  $ xmlstarlet val -d instrument.dtd NS15.xml
-->
<!-- Definitions for the instrument properties are as follows: -->

<!-- 
    instrument: Identifies the instrument and provides a sequence of 
    properties needed to connect to the instrument, to connect to
    the Data Turbine server, and to define the channels of data
    being pushed into the server
 -->
<!ELEMENT instrument (identifier, connectionType, connectionParams, rbnbName, 
                      rbnbServer, rbnbPort, archiveMemory, archiveSize, channels,
                      rawArchiveInterval*, rawArchiveDirectory*)>
<!-- 
    identifier: The string identifier of the instrument (e.g. NS15)
-->
<!ELEMENT identifier (#PCDATA)>

<!-- 
    connectionType: The type of connection to the instrument. 
    Must be one of "socket", "file", or "serial" 
-->
<!ELEMENT connectionType (#PCDATA)>
<!-- 
    connectionParams: The connection parameters for the instrument. 
    Must be one of:
    - "hostName" and "hostPort" for socket connections
    - "filePath" for file connections
    - "serialPort" and "serialPortParams" for serial connections
-->
<!ELEMENT connectionParams ((hostName, hostPort) | filePath | (serialPort, serialPortParams))>

<!--
    hostName: The IP address or fully qualified domain name of the instrument host (e.g 192.168.100.5)
-->
<!ELEMENT hostName (#PCDATA)>

<!--
    hostPort: The TCP port number of the instrument host (e.g. 5111)
-->
<!ELEMENT hostPort (#PCDATA)>

<!--
    filePath: The absolute path to the file on disk with the instrument data (e.g. /path/to/file)
-->
<!ELEMENT filePath (#PCDATA)>

<!--
   serialPort: The computer serial port indicator connected to the instrument (e.g. /dev/tty01) 
-->
<!ELEMENT serialPort (#PCDATA)>

<!--
    serialPortParams: The parameters used in connecting to the instrument over the serial port
-->
<!ELEMENT serialPortParams (baudRate, dataBits, stopBits, parity)>

<!--
    baudRate: The baudRate of the serial connection (e.g. 9600)
-->
<!ELEMENT baudRate (#PCDATA)>

<!--
    dataBits: The data bits of the serial connection (e.g. 8)
-->
<!ELEMENT dataBits (#PCDATA)>

<!--
    stopBits: The stop bits of the serial connection (e.g. 1)
-->
<!ELEMENT stopBits (#PCDATA)>

<!--
    parity: The parity setting of the serial connection (e.g. NONE)
-->
<!ELEMENT parity (#PCDATA)>

<!--
    rbnbName: The name of the instrument source as it appears in the Data Turbine
-->
<!ELEMENT rbnbName (#PCDATA)>

<!--
    rbnbServer: The IP address or host name of the RBNB Data Turbine server (e.g. 127.0.0.1)
-->
<!ELEMENT rbnbServer (#PCDATA)>

<!--
    rbnbPort: The TCP port of the RBNB data Turbine server (e.g. 33333)
-->
<!ELEMENT rbnbPort (#PCDATA)>

<!--
    archiveMemory: The number of in-memory bytes to request for this 
    instrument source in the RBNB Data Turbine server  (e.g. 126000)
-->
<!ELEMENT archiveMemory (#PCDATA)>


<!--
    archiveSize: The number of on-disk bytes to request for this 
    instrument source in the RBNB Data Turbine server  (e.g. 31536000)
-->
<!ELEMENT archiveSize (#PCDATA)>

<!--
    channels: The list of data channels to be created in the DataTurbine for this instrument source
-->
<!ELEMENT channels (channel*)>

<!--
    channel: The details for this instrument's channel data being added to the RBNB server
-->
<!ELEMENT channel (name, dataType, dataPattern, fieldDelimiter, recordDelimiters, dateFormats, dateFields, timeZone)>

<!--
    default: An attribute for the channel indicating if this is the default channel.
    Must be either "true" or "false", and is optional
-->
<!ATTLIST channel default (true|false) "true" >

<!--
    name: The name of the channel
-->
<!ELEMENT name (#PCDATA)>

<!--
    dataType: The type of the incoming data. For now, limited to a value of "String"
-->
<!ELEMENT dataType (#PCDATA)>

<!--
    dataPattern: The regular expression used to match a data sample. Assumes Java RegEx syntax.
    It is best to keep data pattern on one line 
-->
<!ELEMENT dataPattern (#PCDATA)>

<!--
    fieldDelimiter: The character that delimits variables within the sample.
    Use Hex notation for non-printing, whitespace characters (like space) (e.g 0x20)    
-->
<!ELEMENT fieldDelimiter (#PCDATA)>

<!-- 
  recordeDelimiters: The character(s) that delimit records (samples) in a stream or file
  Use Hex notation for non-printing characters, and separate characters with a pipe 
 (e.g. 0x0d|0x0A) (for a carriage return followed by a new line character)
-->
<!ELEMENT recordDelimiters (#PCDATA)>

<!-- 
  dateFormats: The list of date formats for each sample date component that is in a separate variable
  One or more date formats are required, reflecting the date/time variables in the data
  (e.g. mm/dd/YYYY , e.g. HH:MM:SS) (Assumes Java date parsing syntax)
  Note: dateFormat and dateField are used together to locate, then parse the sample date
  -->
<!ELEMENT dateFormats (dateFormat*)>

<!-- 
    dateFields: The list of date fields for each sample date component in a separtate variable
    One or more date fields are required, corresponding to the date/time variable positions in the data
    (e.g 1 , e.g 2) (Correspond to the first and second variables in the data sample)
-->        
<!ELEMENT dateFields (dateField*)>

<!-- 
    timeZone: The time zone identifier that the data were collected in (e.g. UTC)
-->
<!ELEMENT timeZone (#PCDATA)>

<!-- 
  dateFormat: The individual date format for each sample date component that is in a separate variable
  One or more date formats are required, reflecting the date/time variables in the data
  (e.g. mm/dd/YYYY , e.g. HH:MM:SS) (Assumes Java date parsing syntax)
  Note: dateFormat and dateField are used together to locate, then parse the sample date
  -->
<!ELEMENT dateFormat (#PCDATA)>

<!-- 
    dateField: The individual date field for each sample date component in a separtate variable
    One or more date fields are required, corresponding to the date/time variable positions in the data
    (e.g 1 , e.g 2) (Correspond to the first and second variables in the data sample)
-->        
<!ELEMENT dateField (#PCDATA)>

<!--
    rawArchiveInterval: The interval used for archiving raw data files to disk from the DataTurbine
    channel.  Must be either "hourly" or "daily".
-->
<!ELEMENT rawArchiveInterval (#PCDATA)>

<!--
    rawArchiveDirectory: The base directory to archive raw data files created from the DataTurbine
    channel.  Must be writable.
-->
<!ELEMENT rawArchiveDirectory (#PCDATA)>

<!-- TODO:
    processedArchiveInterval: The interval used for archiving processed data files to disk from the DataTurbine
    channel.  Must be either "hourly" or "daily".
<!ELEMENT processedArchiveInterval (#PCDATA)>
-->

<!-- TODO:
    processedArchiveDirectory: The base directory to archive processed data files created from the DataTurbine
    channel.  Must be writable.
<!ELEMENT processedArchiveDirectory (#PCDATA)>
-->

=== csjx/realtime-data/src/test/resources/edu/hawaii/soest/pacioos/text/KANEOHE_CO2-instrument-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE instrument SYSTEM "instrument.dtd">
<instrument>
    <!-- The instrument identifier -->
    <identifier>KANEOHE_CO2</identifier>
    <!-- The connection type: socket, file, or serial -->
    <connectionType>file</connectionType>
    <!-- 
      Configure connection parameters based on connection type. If connection
      type is socket, add hostName and hostPort below. If file, add filePath
      below. If serial, add serialPortParams and sub elements below.
    -->
    <connectionParams> 
        <filePath>
        		/Users/cjones/docs/dev/csjx/realtime-data/src/test/resources/edu/hawaii/soest/pacioos/text/KANEOHE_CO2-mock-data.txt
        	</filePath>
    </connectionParams>
    <!-- The name of the instrument source as it appears in the DataTurbine -->
    <rbnbName>KANEOHE_CO2</rbnbName>
    <!-- The IP or host name of the DataTurbine server -->
    <rbnbServer>127.0.0.1</rbnbServer>
    <!-- The port number of the DataTurbine server -->
    <rbnbPort>33333</rbnbPort>
    <!-- The number of in-memory bytes to request for this instrument source -->
    <archiveMemory>50000</archiveMemory>
    <!-- The number of on-disk bytes to request for this instrument source -->
    <archiveSize>31536000</archiveSize>
    <!-- The list of data channels to be created in the DataTurbine for this instrument source -->
    <channels>
        <!-- The default channel details. This will push ASCII data into the DataTurbine -->
        <channel default="true">
            <!-- The name of the channel -->
            <name>DecimalASCIISampleData</name>
            <!-- The channel's incoming data type -->
            <dataType>String</dataType>
            <!-- data archive example:
			# 100.86 , 429.8 , 396.1 , NaN , 34.71 , 26.62 , 2.70 , 2.19 , 193.81 , 6.20 , 189.54 , 22.62 , 08 Oct 2016 15:17:00
			# 100.96 , 473.5 , 395.5 , NaN , 34.74 , 26.59 , 5.66 , 1.67 , 184.19 , 5.89 , 180.12 , 22.65 , 08 Oct 2016 18:17:00
			# 100.94 , 472.6 , 395.4 , NaN , 34.74 , 26.85 , 4.25 , 2.01 , 197.30 , 6.31 , 192.96 , 22.57 , 08 Oct 2016 21:17:00
			# 100.74 , 453.0 , 395.2 , NaN , 34.74 , 26.99 , 21.00 , 8.98 , 202.75 , 6.49 , 198.30 , 22.52 , 09 Oct 2016 00:17:00
			# 100.77 , 433.1 , 394.5 , NaN , 34.71 , 26.93 , 10.43 , 7.35 , 211.02 , 6.75 , 206.38 , 22.52 , 09 Oct 2016 03:17:00
			# 100.93 , 421.1 , 395.6 , NaN , 34.71 , 26.88 , 4.43 , 5.11 , 204.38 , 6.54 , 199.88 , 22.54 , 09 Oct 2016 06:17:00
			# 100.98 , 424.7 , 395.6 , NaN , 34.72 , 26.81 , 11.38 , 16.58 , 200.85 , 6.43 , 196.43 , 22.56 , 09 Oct 2016 09:17:00
			# 100.85 , 436.8 , 395.5 , NaN , 34.73 , 26.78 , 2.18 , 1.62 , 197.68 , 6.33 , 193.33 , 22.58 , 09 Oct 2016 12:17:00
			# 100.81 , 456.3 , 396.0 , NaN , 34.74 , 26.75 , 7.86 , 6.84 , 196.25 , 6.28 , 191.92 , 22.60 , 09 Oct 2016 15:17:00
			# 100.93 , 445.9 , 395.6 , NaN , 34.73 , 26.73 , 16.43 , 9.23 , 191.19 , 6.12 , 186.98 , 22.60 , 09 Oct 2016 18:17:00
			# 100.96 , 442.6 , 395.5 , NaN , 34.73 , 26.91 , 25.46 , 19.47 , 192.84 , 6.17 , 188.60 , 22.54 , 09 Oct 2016 21:17:00
			# 100.78 , 449.2 , 395.2 , NaN , 34.73 , 27.25 , 4.21 , 0.50 , 196.55 , 6.29 , 192.24 , 22.44 , 10 Oct 2016 00:17:00
            -->
            <!-- example DT sample:
			curl -s -o - "http://bbl.ancl.hawaii.edu:8080/RBNB/KANEOHE_CO2/DecimalASCIISampleData" | od -ax
			0000000    #  sp   1   0   0   .   7   8  sp   ,  sp   4   4   9   .   2
			             2023    3031    2e30    3837    2c20    3420    3934    322e
			0000020   sp   ,  sp   3   9   5   .   2  sp   ,  sp   N   a   N  sp   ,
			             2c20    3320    3539    322e    2c20    4e20    4e61    2c20
			0000040   sp   3   4   .   7   3  sp   ,  sp   2   7   .   2   5  sp   ,
			             3320    2e34    3337    2c20    3220    2e37    3532    2c20
			0000060   sp   4   .   2   1  sp   ,  sp   0   .   5   0  sp   ,  sp   1
			             3420    322e    2031    202c    2e30    3035    2c20    3120
			0000100    9   6   .   5   5  sp   ,  sp   6   .   2   9  sp   ,  sp   1
			             3639    352e    2035    202c    2e36    3932    2c20    3120
			0000120    9   2   .   2   4  sp   ,  sp   2   2   .   4   4  sp   ,  sp
			             3239    322e    2034    202c    3232    342e    2034    202c
			0000140    1   0  sp   O   c   t  sp   2   0   1   6  sp   0   0   :   1
			             3031    4f20    7463    3220    3130    2036    3030    313a
			0000160    7   :   0   0  cr  nl
			             3a37    3030    0a0d
			0000166
            -->
            <!-- 
              The regular expression used to match a data sample.
              Best to keep the data pattern on one line below 
            -->
            <dataPattern>#\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\S+,\s*\d{2} \S{3} \d{4} \d{2}:\d{2}:\d{2}\s*</dataPattern>
            <!-- 
              The character that delimits variables within the sample
              Use Hex notation for non-printing, whitespace characters (like space)
            -->
            <fieldDelimiter>,</fieldDelimiter>
            <!-- 
              The character(s) that delimit records (samples) in a stream or file
              Use Hex notation for non-printing characters, separate characters with a pipe
            -->
            <recordDelimiters>0x0d|0x0A</recordDelimiters>
            <!-- 
              The list of date formats for each sample date component in a separtate variable
              One or more date formats are required, reflecting the date/time variables in the data
              Note: dateFormat and dateField are used together to locate, then parse the sample date
              -->
            <dateFormats>
                <dateFormat>dd MMM yyyy HH:mm:ss</dateFormat> 
            </dateFormats>
            <!-- 
              The list of date fields for each sample date component in a separtate variable
              One or more date fields are required, corresponding to the date/time variable positions in the data 
            -->        
            <dateFields>
                <dateField>13</dateField>
            </dateFields>
            <!-- The time zone identifier that the data were collected in -->
            <timeZone>Pacific/Honolulu</timeZone>
        </channel>
    </channels>   
</instrument>

=== csjx/realtime-data/conf/AW01XX_002CTDXXXXR00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE instrument SYSTEM "instrument.dtd">
<instrument>
    <!-- The instrument identifier -->
    <identifier>AW01XX_002CTDXXXXR00</identifier>
    <!-- The connection type: socket, file, or serial -->
    <connectionType>socket</connectionType>
    <!-- 
      Configure connection parameters based on connection type. If connection
      type is socket, add hostName and hostPort below. If file, add filePath
      below. If serial, add serialPortParams and sub elements below.
    -->
    <connectionParams> 
        <hostName>68.25.35.242</hostName>
        <hostPort>5111</hostPort>
    </connectionParams>
    <!-- The name of the instrument source as it appears in the DataTurbine -->
    <rbnbName>AW01XX_002CTDXXXXR00</rbnbName>
    <!-- The IP or host name of the DataTurbine server -->
    <rbnbServer>realtime.pacioos.hawaii.edu</rbnbServer>
    <!-- The port number of the DataTurbine server -->
    <rbnbPort>3333</rbnbPort>
    <!-- The number of in-memory bytes to request for this instrument source -->
    <archiveMemory>50000</archiveMemory>
    <!-- The number of on-disk bytes to request for this instrument source -->
    <archiveSize>31536000</archiveSize>
    <!-- The list of data channels to be created in the DataTurbine for this instrument source -->
    <channels>
        <!-- The default channel details. This will push ASCII data into the DataTurbine -->
        <channel default="true">
            <!-- The name of the channel -->
            <name>DecimalASCIISampleData</name>
            <!-- The channel's incoming data type -->
            <dataType>String</dataType>
            <!-- data archive example:
            # 26.0505,  5.00960,    0.406, 0.1835, 0.1533,  32.0562, 22 Mar 2013 16:01:11
            # 25.7813,  5.08190,    0.421, 0.1758, 0.1531,  32.7674, 22 Mar 2013 16:05:11
            # 25.5295,  5.13902,    0.409, 0.1394, 0.1649,  33.3646, 22 Mar 2013 16:09:11
            # 26.1928,  4.98592,    0.356, 0.2123, 0.1539,  31.7879, 22 Mar 2013 16:13:11
            # 25.7245,  5.08019,    0.349, 0.2344, 0.1519,  32.7958, 22 Mar 2013 16:17:11
            # 25.8939,  5.06251,    0.367, 0.1757, 0.1515,  32.5471, 22 Mar 2013 16:21:11
            # 25.5735,  5.14871,    0.376, 0.1968, 0.1866,  33.4031, 22 Mar 2013 16:25:11
            # 25.8623,  5.08455,    0.295, 0.2356, 0.1552,  32.7287, 22 Mar 2013 16:29:11
            # 25.9927,  5.07034,    0.502, 0.2581, 0.1574,  32.5333, 22 Mar 2013 16:33:11
            # 25.6895,  5.12890,    0.444, 0.2250, 0.1612,  33.1743, 22 Mar 2013 16:37:11
            -->
            <!-- example DT sample:
            curl -s -o - http://realtime.pacioos.hawaii.edu:8080/RBNB/AW01XX_002CTDXXXXR00/DecimalASCIISampleData | od -ax
            0000000   #  sp   2   6   .   0   1   2   5   ,  sp  sp   5   .   1   1
                    2023 3632 302e 3231 2c35 2020 2e35 3131
            0000020   8   3   5   ,  sp  sp  sp   -   0   .   1   1   7   ,  sp   0
                    3338 2c35 2020 2d20 2e30 3131 2c37 3020
            0000040   .   1   5   2   8   ,  sp   0   .   1   4   5   1   ,  sp  sp
                    312e 3235 2c38 3020 312e 3534 2c31 2020
            0000060   3   2   .   8   6   5   1   ,  sp   2   2  sp   M   a   r  sp
                    3233 382e 3536 2c31 3220 2032 614d 2072
            0000100   2   0   1   3  sp   1   9   :   1   3   :   1   1  cr  nl nul
                    3032 3331 3120 3a39 3331 313a 0d31 000a
            0000117
            -->
            <!-- 
              The regular expression used to match a data sample.
              Best to keep the data pattern on one line below 
            -->
            <dataPattern># \S*, *\S*, *\S*, *\S*, *\S*, *\S*, *\d{2} \S{3} \d{4} \d{2}:\d{2}:\d{2}\s*</dataPattern>
            <!-- 
              The character that delimits variables within the sample
              Use Hex notation for non-printing, whitespace characters (like space)
            -->
            <fieldDelimiter>,</fieldDelimiter>
            <!-- 
              The character(s) that delimit records (samples) in a stream or file
              Use Hex notation for non-printing characters, separate characters with a pipe
            -->
            <recordDelimiters>0x0D|0x0A</recordDelimiters>
            <!-- 
              The list of date formats for each sample date component in a separate variable
              One or more date formats are required, reflecting the date/time variables in the data
              Note: dateFormat and dateField are used together to locate, then parse the sample date
              -->
            <dateFormats>
              <dateFormat>dd MMM yyyy HH:mm:ss</dateFormat> 
            </dateFormats>
            <!-- 
              The list of date fields for each sample date component in a separate variable
              One or more date fields are required, corresponding to the date/time variable positions in the data 
            -->        
            <dateFields>
              <dateField>7</dateField>
            </dateFields>
            <!-- The time zone identifier that the data were collected in -->
            <timeZone>Pacific/Honolulu</timeZone>
            <!-- The list of data archivers used to write data to disk -->
            <archivers>
                <!-- Write the raw data to /data/raw -->
                <archiver>
                    <archiveType>raw</archiveType>
                    <archiveInterval>hourly</archiveInterval>
                    <archiveBaseDirectory>/data/raw/alawai</archiveBaseDirectory>
                </archiver>
                <!-- Write the PacIOOS 2020 formatted data to /data/processed -->
                <!--
                <archiver>
                    <archiveType>pacioos-2020-format</archiveType>
                    <archiveInterval>daily</archiveInterval>
                    <archiveBaseDirectory>/data/processed/pacioos</archiveBaseDirectory>
                </archiver>
                -->
            </archivers>
        </channel>
    </channels>
</instrument>

=== csjx/realtime-data/conf/MB01XX_001CTDXXXXR00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE instrument SYSTEM "instrument.dtd">
<instrument>
    <!-- The instrument identifier -->
    <identifier>MB01XX_001CTDXXXXR00</identifier>
    <!-- The connection type: socket, file, or serial -->
    <connectionType>socket</connectionType>
    <!-- 
      Configure connection parameters based on connection type. If connection
      type is socket, add hostName and hostPort below. If file, add filePath
      below. If serial, add serialPortParams and sub elements below.
    -->
    <connectionParams> 
        <hostName>24.221.193.197</hostName>
        <hostPort>5111</hostPort>
    </connectionParams>
    <!-- The name of the instrument source as it appears in the DataTurbine -->
    <rbnbName>MB01XX_001CTDXXXXR00</rbnbName>
    <!-- The IP or host name of the DataTurbine server -->
    <rbnbServer>realtime.pacioos.hawaii.edu</rbnbServer>
    <!-- The port number of the DataTurbine server -->
    <rbnbPort>3333</rbnbPort>
    <!-- The number of in-memory bytes to request for this instrument source -->
    <archiveMemory>50000</archiveMemory>
    <!-- The number of on-disk bytes to request for this instrument source -->
    <archiveSize>31536000</archiveSize>
    <!-- The list of data channels to be created in the DataTurbine for this instrument source -->
    <channels>
        <!-- The default channel details. This will push ASCII data into the DataTurbine -->
        <channel default="true">
            <!-- The name of the channel -->
            <name>DecimalASCIISampleData</name>
            <!-- The channel's incoming data type -->
            <dataType>String</dataType>
            <!-- data archive example:
            # 24.3613,  5.25591,    1.752, 0.1265, 0.4915,  35.1153, 22 Dec 2016 08:00:53
            # 24.3607,  5.25586,    1.733, 0.1228, 0.4904,  35.1153, 22 Dec 2016 08:04:53
            # 24.3596,  5.25568,    1.753, 0.1266, 0.4903,  35.1149, 22 Dec 2016 08:08:53
            # 24.3520,  5.25498,    1.738, 0.1290, 0.4914,  35.1155, 22 Dec 2016 08:12:53
            # 24.3448,  5.25434,    1.758, 0.1288, 0.5001,  35.1164, 22 Dec 2016 08:16:53
            # 24.3416,  5.25393,    1.761, 0.1279, 0.4877,  35.1158, 22 Dec 2016 08:20:53
            # 24.3415,  5.25377,    1.744, 0.1279, 0.4843,  35.1147, 22 Dec 2016 08:24:53
            # 24.3426,  5.25378,    1.781, 0.1276, 0.4866,  35.1139, 22 Dec 2016 08:28:53
            # 24.3439,  5.25391,    1.790, 0.1285, 0.4952,  35.1138, 22 Dec 2016 08:32:53
            # 24.3394,  5.25347,    1.766, 0.1279, 0.4829,  35.1140, 22 Dec 2016 08:36:53
            -->
            <!-- example DT sample:
            curl -s -o - http://realtime.pacioos.hawaii.edu:8080/RBNB/MB01XX_001CTDXXXXR00/DecimalASCIISampleData | od -ax
            0000000   #  sp   2   4   .   3   3   9   3   ,  sp  sp   5   .   2   5
                    2023 3432 332e 3933 2c33 2020 2e35 3532
            0000020   3   7   0   ,  sp  sp  sp  sp   1   .   7   6   1   ,  sp   0
                    3733 2c30 2020 2020 2e31 3637 2c31 3020
            0000040   .   1   3   1   5   ,  sp   0   .   4   8   3   9   ,  sp  sp
                    312e 3133 2c35 3020 342e 3338 2c39 2020
            0000060   3   5   .   1   1   5   9   ,  sp   2   2  sp   D   e   c  sp
                    3533 312e 3531 2c39 3220 2032 6544 2063
            0000100   2   0   1   6  sp   0   9   :   2   8   :   5   3  cr  nl nul
                    3032 3631 3020 3a39 3832 353a 0d33 000a
            0000117
            -->
            <!-- 
              The regular expression used to match a data sample.
              Best to keep the data pattern on one line below 
            -->
            <dataPattern># [\S]*,[ ]*[\S]*,[ ]*[\S]*,[ ]*[\S]*,[ ]*[\S]*,[ ]*[\S]*,[ ]*\d{2} [\S]{3} \d{4} \d{2}:\d{2}:\d{2}\s*</dataPattern>
            <!-- 
              The character that delimits variables within the sample
              Use Hex notation for non-printing, whitespace characters (like space)
            -->
            <fieldDelimiter>,</fieldDelimiter>
            <!-- 
              The character(s) that delimit records (samples) in a stream or file
              Use Hex notation for non-printing characters, separate characters with a pipe
            -->
            <recordDelimiters>0x0d|0x0A</recordDelimiters>
            <!-- 
              The list of date formats for each sample date component in a separate variable
              One or more date formats are required, reflecting the date/time variables in the data
              Note: dateFormat and dateField are used together to locate, then parse the sample date
              -->
            <dateFormats>
                <dateFormat>dd MMM yyyy HH:mm:ss</dateFormat> 
            </dateFormats>
            <!-- 
              The list of date fields for each sample date component in a separate variable
              One or more date fields are required, corresponding to the date/time variable positions in the data 
            -->        
            <dateFields>
              <dateField>7</dateField>
            </dateFields>
            <!-- The time zone identifier that the data were collected in -->
            <timeZone>HST</timeZone>
            <!-- The list of data archivers used to write data to disk -->
            <archivers>
                <!-- Write the raw data to /data/raw -->
                <archiver>
                    <archiveType>raw</archiveType>
                    <archiveInterval>hourly</archiveInterval>
                    <archiveBaseDirectory>/data/raw/alawai</archiveBaseDirectory>
                </archiver>
                <!-- Write the PacIOOS 2020 formatted data to /data/processed -->
                <!--
                <archiver>
                    <archiveType>pacioos-2020-format</archiveType>
                    <archiveInterval>hourly</archiveInterval>
                    <archiveBaseDirectory>/data/processed/pacioos</archiveBaseDirectory>
                </archiver>
                -->
            </archivers>
        </channel>
    </channels>
</instrument>
